// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ErrorCatcher
{
				static class Vsix
				{
								public const string Id = "376e6cdc-893d-4ae7-ad93-325575c35301";
								public const string Name = "Error Catcher II";
								public const string Description = @"The easiest way to make sure not to miss any errors or warnings in any code file.";
								public const string Language = "en-US";
								public const string Version = "1.2";
								public const string Author = "Mads Kristensen";
								public const string Tags = "error, exception";
				}
}
